version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      # Only allow patch as minor babel versions need to be upgraded all together
      - dependency-name: '@babel/*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

      - dependency-name: '*'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-major'

    labels:
      - 'source: dependencies'
      - 'pr: chore'
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    labels:
      - 'source: dependencies'
      - 'pr: chore'
