backend:
  - '.github/actions/yarn-nm-install/*.yml'
  - '.github/workflows/**'
  - 'packages/**/package.json'
  - 'packages/**/server/**/*.(js|ts)'
  - 'packages/**/strapi-server.js'
  - 'packages/{utils,generators,cli,providers}/**'
  - 'packages/core/*/{lib,bin,ee,src}/**'
  - 'tests/api/**'
  - 'packages/core/database/**'
frontend:
  - '.github/actions/yarn-nm-install/*.yml'
  - '.github/workflows/**'
  - 'packages/**/package.json'
  - 'packages/**/admin/src/**'
  - 'packages/**/admin/ee/admin/**'
  - 'packages/**/strapi-admin.js'
  - 'packages/admin-test-utils/**'
