sudo: required

git:
  depth: 1

language: node_js

node_js:
  - "7"
  - "8"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@latest
  - npm -v
  - sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

install:
  - npm install

script:
  - npm run test
