sudo: required

git:
  depth: 1

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn run setup

node_js:
  - "7"

sudo: false

script:
  - yarn run test
