sudo: required

git:
  depth: 1

language: node_js

install:
  - cd packages/strapi-mongoose
  - npm link
  - cd ../strapi
  - npm link strapi-mongoose
  - npm install
  - cd ..
  - cd ..
  - npm install

node_js:
  - "7"

sudo: false

script:
  - npm test
