sudo: required

git:
  depth: 1

language: node_js

install:
  - cd packages/strapi-mongoose
  - npm link
  - cd ../strapi-generate-admin
  - npm link
  - cd ../strapi
  - npm link strapi-mongoose
  - npm link strapi-generate-admin
  - npm install
  - cd ./node_modules/koa-joi-router
  - sed -i.bu 's/await-busboy/co-busboy/' joi-router.js
  - npm install co-busboy
  - cd ..
  - cd ..
  - cd ..
  - cd ..
  - npm install

node_js:
  - "7"

sudo: false

script:
  - npm test
