sudo: required

git:
  depth: 1

language: node_js

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - cd packages/strapi-utils
  - npm link
  - cd ../strapi-mongoose
  - npm link strapi-utils
  - npm link
  - cd ../strapi-bookshelf
  - npm link strapi-utils
  - npm link
  - cd ../strapi-generate-migrations
  - npm link strapi-bookshelf
  - npm link strapi-utils
  - npm link
  - cd ../strapi-generate
  - npm link strapi-utils
  - npm link
  - cd ../strapi-generate-admin
  - npm link strapi-utils
  - npm link
  - cd ../strapi-generate-api
  - npm link
  - cd ../strapi-generate-policy
  - npm link
  - cd ../strapi-generate-service
  - npm link
  - cd ../strapi-generate-new
  - npm link strapi-utils
  - npm link
  - cd ../strapi
  - npm link strapi-generate-new
  - npm link strapi-generate
  - npm link strapi-generate-admin
  - npm link strapi-generate-api
  - npm link strapi-generate-policy
  - npm link strapi-generate-service
  - npm link strapi-generate-migrations
  - npm link strapi-mongoose
  - npm link strapi-utils
  - npm install
  - cd ./node_modules/koa-joi-router
  - sed -i.bu 's/await-busboy/co-busboy/' joi-router.js
  - npm install co-busboy
  - cd ..
  - cd ..
  - cd ..
  - cd ..
  - npm install

node_js:
  - "7"

sudo: false

script:
  - npm test
