services:
  - mongodb
  - postgresql

sudo: required
dist: trusty

language: node_js

node_js:
  - '10'
  # - '11'

install:
  - npm run setup:build
  - npm install -g wait-on
  - cypress install

before_script:
  - psql -c 'create database strapi_test;' -U postgres

script:
  # run snyk
  - npm run -s test:snyk

  # default unit test
  - npm run -s test:unit

  # e2e trests
  - npm run -s test:generate-app --dbclient=postgres --dbhost=localhost --dbport=5432 --dbname=strapi_test --dbusername=postgres --dbpassword=
  - npm run -s test:start-app & wait-on http://localhost:1337
  - npm run -s test:e2e

  # cypress tests
  - npm run -s test:generate-app --dbclient=mongo --dbhost=localhost --dbport=27017 --dbname=strapi_test --dbusername= --dbpassword=
  - npm run -s test:start-app & wait-on http://localhost:1337
  - npm run -s cypress:run

  # lint and doc
  - npm run -s lint
  - npm run -s doc

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
