nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

defaultSemverRangePrefix: ''

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
