name: Admin bundle-size

on:
  pull_request:
    paths:
      - '**/admin/src/**.js'
      - '**/helper-plugin/lib/src/**.js'
      - '**/translations/**.json'
      - 'yarn.lock'

jobs:
  admin_size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: '**/build/**/*.{js,css,html,svg}'
          strip-hash: "\\.(?:(\\w{8})\\.chunk)|(?:\\.(\\w{8}))"
