name: 'Tests'

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**.mdx?'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yaml

  pretty:
    name: 'pretty (node: ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  lint:
    name: 'lint (node: ${{ matrix.node }})'
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  build:
    name: 'build (node: ${{ matrix.node }})'
    needs: [changes]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  typescript:
    name: 'typescript (node: ${{ matrix.node }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  unit_back:
    name: 'unit_back (node: ${{ matrix.node }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  unit_front:
    name: 'unit_front (node: ${{ matrix.node }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - run: echo "Skipped"

  e2e_ce:
    name: '[CE] e2e (browser: ${{ matrix.project }}) (shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['chromium', 'webkit', 'firefox']
        shard: [1/2, 2/2]
    steps:
      - run: echo "Skipped"

  e2e_ee:
    name: '[EE] e2e (browser: ${{ matrix.project }}) (shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['chromium', 'webkit', 'firefox']
        shard: [1/2, 2/2]
    steps:
      - run: echo "Skipped"

  cli:
    name: 'CLI Tests (node: ${{ matrix.node }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - run: echo "Skipped"

  api_ce_pg:
    name: '[CE] API Integration (postgres, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"

  api_ce_mysql:
    name: '[CE] API Integration (mysql:latest, package: mysql2, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"

  api_ce_sqlite:
    name: '[CE] API Integration (sqlite, package: better-sqlite3, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"

  api_ee_pg:
    name: '[EE] API Integration (postgres, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"

  api_ee_mysql:
    name: '[EE] API Integration (mysql:latest, package: mysql2, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"

  api_ee_sqlite:
    name: '[EE] API Integration (sqlite, client: better-sqlite3, node: ${{ matrix.node }}, shard: ${{ matrix.shard }})'
    needs: [changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - run: echo "Skipped"
